apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-config
  labels:
    draft: {{ default "draft-app" .Values.draft }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
data:
  application.properties: |-
    spring.datasource.url=jdbc:postgresql://{{ .Release.Name }}-postgres:5432/postgres <1>
