# Default values for Maven projects.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: draft
  tag: dev
  pullPolicy: IfNotPresent
service:
  name: jx-sample-spring-data-postgresql
  type: ClusterIP
  externalPort: 80
  internalPort: 8080
  annotations:
    fabric8.io/expose: "true"
    fabric8.io/ingress.annotations: "kubernetes.io/ingress.class: nginx"
    release_time: "{{ .Release.Time }}"
    release_name: "{{ .Release.Name }}"
    creation_date: "{{ now }}"
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 400m
    memory: 512Mi
probePath: /actuator/health
livenessProbe:
  initialDelaySeconds: 60
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
readinessProbe:
  periodSeconds: 60
  successThreshold: 1
  timeoutSeconds: 1
terminationGracePeriodSeconds: 10
## Sub chart values
#postgres:
#  postgresPassword: "notVerySec"
